game_score: 5001
# cm3:
#   enabled: false
# favorite:
#   food: none
cm3:
  something: something

favorite:
  drink: coffee
  food: pizza

pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
  - pineapple


job:
  enabled: true
  containers:
    - name: sample
      file_name: db/schema.sql
    - name: sample2
      file_name: db/schema.sql